clip_templates = [
    'a bad photo of a {},',
    'a photo of many {},',
    'a photo of the hard to see {},',
    'a low resolution photo of the {}, a type of bird,',
    'a rendering of a {},',
    'a bad photo of the {}, a type of bird,',
    'a cropped photo of the {}, a type of bird,',
    'a photo of a hard to see {},',
    'a bright photo of a {},',
    'a photo of a clean {},',
    'a photo of a dirty {},',
    'a drawing of a {},',
    'a photo of my {}, a type of bird,',
    'a photo of the cool {},',
    'a close-up photo of a {},',
    'a black and white photo of the {}, a type of bird,',
    'a painting of the {}, a type of bird,',
    'a painting of a {}, a type of bird,',
    'a bright photo of the {}, a type of bird,',
    'a cropped photo of a {},',
    'a plastic {}, a type of bird,',
    'a photo of the dirty {},',
    'a jpeg corrupted photo of a {}, a type of bird,',
    'a blurry photo of the {}, a type of bird,',
    'a photo of the {}, a type of bird,',
    'a good photo of the {}, a type of bird,',
    'a rendering of the {}, a type of bird,',
    'a {} in a video game, a type of bird,',
    'a photo of one {}, a type of bird,',
    'a close-up photo of the {}, a type of bird,',
    'a photo of a {}, a type of bird,',
    'a low resolution photo of a {}, a type of bird,',
    'a rendition of the {}, a type of bird,',
    'a photo of the clean {}, a type of bird,',
    'a rendition of a {},',
    'a photo of a nice {},',
    'a photo of a weird {},',
    'a blurry photo of a {},',
    'a good photo of a {},',
    'a plushie {}, a type of bird,',
    'a photo of the nice {},',
    'a photo of the weird {},',
    'a photo of the large {},',
    'a toy {}, a  type of bird,',
    'itap of my {},',
    'a photo of a cool {},']

