annotation_path = '#/oven/CUB_visual_descriptions.json'
bbox_path = '#/datasets/CUB/CUB_200_2011/bboxes/bounding_boxes.json'
bbox_path_val = '#/datasets/CUB/CUB_200_2011/bboxes/bounding_boxes_bird_beak_val.json'
max_boxes = 5
# max_boxes_beak = 2
# bbox_path_beak = '#/datasets/CUB/CUB_200_2011/bboxes/bounding_boxes_bird_beak.json'
cub_vondrick_description = '#/classify_by_description_release/descriptors/descriptors_cub.json'
max_descriptions = 13
ROOT ='#/cub_logs/'
eval_every = 5